export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  AZAAM_STAFF = 'AZAAM_STAFF',
  UNIVERSITY_ADMIN = 'UNIVERSITY_ADMIN',
  UNIVERSITY_STAFF = 'UNIVERSITY_STAFF',
  ORGANIZATION_ADMIN = 'ORGANIZATION_ADMIN',
  ORGANIZATION_STAFF = 'ORGANIZATION_STAFF',
  CLINICAL_SUPERVISOR = 'CLINICAL_SUPERVISOR',
  STUDENT = 'STUDENT',
  INDEPENDENT_APPLICANT = 'INDEPENDENT_APPLICANT',
}

export enum ApplicantType {
  UNIVERSITY = 'UNIVERSITY',
  INDEPENDENT = 'INDEPENDENT',
}

export enum ApplicationStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  DOCUMENTS_REQUIRED = 'DOCUMENTS_REQUIRED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PLACEMENT_PENDING = 'PLACEMENT_PENDING',
  PLACED = 'PLACED',
  SUPERVISOR_ASSIGNED = 'SUPERVISOR_ASSIGNED',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  CERTIFICATE_ISSUED = 'CERTIFICATE_ISSUED',
}

export enum PlacementStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum ClinicalAttachmentStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum AttendanceStatus {
  PRESENT = 'PRESENT',
  ABSENT = 'ABSENT',
  EXCUSED = 'EXCUSED',
}

export enum LogbookStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  REVISION_REQUESTED = 'REVISION_REQUESTED',
}

export enum EvaluationType {
  MID_TERM = 'MID_TERM',
  FINAL = 'FINAL',
}

export enum CertificateStatus {
  ISSUED = 'ISSUED',
  REVOKED = 'REVOKED',
}

export enum DocumentStatus {
  UPLOADED = 'UPLOADED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum DocumentCategory {
  PASSPORT = 'PASSPORT',
  MEDICAL_LICENSE = 'MEDICAL_LICENSE',
  UNIVERSITY_LETTER = 'UNIVERSITY_LETTER',
  ENROLLMENT_STUDENT_ID = 'ENROLLMENT_STUDENT_ID',
  CV = 'CV',
  INSURANCE = 'INSURANCE',
  IMMUNIZATION = 'IMMUNIZATION',
  APPLICATION_SUPPORTING_DOC = 'APPLICATION_SUPPORTING_DOC',
  SUPERVISOR_CREDENTIAL = 'SUPERVISOR_CREDENTIAL',
  CERTIFICATE = 'CERTIFICATE',
  OTHER = 'OTHER',
}

export enum DocumentOwnerType {
  STUDENT = 'Student',
  APPLICATION = 'Application',
  PLACEMENT = 'Placement',
  CLINICAL_ATTACHMENT = 'ClinicalAttachment',
  CERTIFICATE = 'Certificate',
  UNIVERSITY = 'University',
  ORGANIZATION = 'Organization',
  CLINICAL_SUPERVISOR = 'ClinicalSupervisor',
}

export enum OrganizationType {
  HOSPITAL = 'HOSPITAL',
  CLINIC = 'CLINIC',
  MEDICAL_CENTER = 'MEDICAL_CENTER',
  HEALTH_CENTER = 'HEALTH_CENTER',
  TEACHING_HOSPITAL = 'TEACHING_HOSPITAL',
  SPECIALIZED_CENTER = 'SPECIALIZED_CENTER',
  HEALTHCARE_FACILITY = 'HEALTHCARE_FACILITY',
  OTHER = 'OTHER',
}

export interface AuthUser {
  userId: string;
  email: string;
  roles: UserRole[];
  universityId?: string | null;
  organizationId?: string | null;
  studentId?: string | null;
}
